<li><a href="${pageContext.request.contextPath}/products?product=1"><img src="${pageContext.request.contextPath}/static/images/products/img-c001-001.jpg" alt="" /></a></li>
<li><a href="${pageContext.request.contextPath}/products?product=2"><img src="${pageContext.request.contextPath}/static/images/products/img-c001-002.jpg" alt="" /></a></li>
<li><a href="${pageContext.request.contextPath}/products?product=3"><img src="${pageContext.request.contextPath}/static/images/products/img-c001-003.jpg" alt="" /></a></li>
<li><a href="${pageContext.request.contextPath}/products?product=4"><img src="${pageContext.request.contextPath}/static/images/products/img-c002-004.jpg" alt="" /></a></li>
<li><a href="${pageContext.request.contextPath}/products?product=5"><img src="${pageContext.request.contextPath}/static/images/products/img-c002-005.jpg" alt="" /></a></li>
<li><a href="${pageContext.request.contextPath}/products?product=6"><img src="${pageContext.request.contextPath}/static/images/products/img-c002-006.jpg" alt="" /></a></li>
<li><a href="${pageContext.request.contextPath}/products?product=7"><img src="${pageContext.request.contextPath}/static/images/products/img-c003-007.jpg" alt="" /></a></li>
<li><a href="${pageContext.request.contextPath}/products?product=8"><img src="${pageContext.request.contextPath}/static/images/products/img-c003-008.jpg" alt="" /></a></li>
<li><a href="${pageContext.request.contextPath}/products?product=9"><img src="${pageContext.request.contextPath}/static/images/products/img-c003-009.jpg" alt="" /></a></li>
